framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(RABBITMQ_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
                options:
                    retry_strategy:
                        max_retries: 1
                    queues:
                        main:
                            queue_options:

            failed:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    retry_strategy:
                        max_retries: 10
                        delay: 10000
                    queues:
                        fail:
                            queue_options:
                                arguments:

        routing:
            # Route your messages to the transports
            'App\Message\EmailMessage': async
            'App\Message\PhoneMessage': async